branch: master
commitSha: ""
type: "config" # config or nonconfig
replicas: 3
image:
  registry: "docker.io"
  repository: "corfudb/corfu-server"
  tag: "0.3.2-SNAPSHOT"
  pullPolicy: Always
pythonImage:
  registry: "docker.io"
  repository: "python"
  tag: "3.8-buster"
  pullPolicy: Always
persistence:
  enabled: true
  storageSize: 2Gi
  storageClass: "local-path"
resources: {}
service:
  port: 9000
