{{- if .Values.tls.certificate.enabled }}
{{- $dns := printf "*.%s-headless.%s.svc.cluster.local" .Values.nameOverride .Release.Namespace }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.tls.certificate.certificateName }}
  labels:
    {{- include "corfu.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.tls.secretName }}
  commonName: corfu
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  keystores:
    jks:
      create: true
      passwordSecretRef:
        name: {{ .Values.tls.passwordName }}
        key: password
  usages:
    - server auth
    - client auth
  dnsNames:
    - corfu
    - corfu2
    - "{{ $dns }}"
  issuerRef:
    name: {{ .Values.tls.certificate.issuer.name }}
    kind: {{ .Values.tls.certificate.issuer.kind }}
    group: cert-manager.io
{{- end }}