apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "corfu.fullname" . }}-corfu-configs-lr
  labels:
  {{- include "corfu.labels" . | indent 4 }}
data:
  {{- with .Files.Glob "serial_number/*" }}
  {{- .AsConfig | nindent 2 }}
  {{- end }}
