apiVersion: v1
kind: ConfigMap
metadata:
  name: corfu-layout-configs
  labels:
  {{- include "corfu.labels" . | indent 4 }}
data:
  {{- with .Files.Glob "files/*" }}
  {{- .AsConfig | nindent 2 }}
  {{- end }}
