apiVersion: v1
kind: Service
metadata:
  name: {{ include "corfu.fullname" . }}
  labels:
    {{- include "corfu.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "corfu.selectors" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "corfu.fullname" . }}-health
  labels:
    {{- include "corfu.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.healthPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "corfu.selectors" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "corfu.fullname" . }}-headless
  labels:
    {{- include "corfu.labels" . | indent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "corfu.selectors" . | nindent 4 }}
