{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "corfu.serviceAccountName" . }}
  labels:
    {{- include "corfu.labels" . | indent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "corfu.serviceAccountName" . }}
  labels:
    {{- include "corfu.labels" . | indent 4 }}
rules:
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames:
      - {{ .Values.podSecurityPolicy.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "corfu.name" . }}-role-binding
  labels:
    {{- include "corfu.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "corfu.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "corfu.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}