apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "corfu.fullname" . }}
  labels:
    {{- include "corfu.labels" . | indent 4 }}
spec:
  serviceName: {{ include "corfu.fullname" . }}-headless
  replicas: {{ include "corfu.replicas" . }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "corfu.selectors" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "corfu.selectors" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecretsEnabled }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "corfu.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "corfu.fullname" . }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "sh"
            - "-c"
            - |
              java \
              $(JAVA_OPTS) \
              -cp *.jar \
              {{- if .Values.logPersistence.enabled }}
              -Dlogback.configurationFile=/usr/share/corfu/conf/logback.prod.xml \
              {{- end }}
              org.corfudb.infrastructure.CorfuServer \
              -a $POD_NAME.corfu-headless.$POD_NAMESPACE.svc.cluster.local \
              {{- if .Values.persistence.enabled }}
              -l /config \
              {{- else }}
              -m \
              {{- end }}
              {{- if .Values.tls.enabled }}
              --enable-tls --enable-tls-mutual-auth --keystore=/certs/keystore.jks  --truststore=/certs/truststore.jks \
              --keystore-password-file=/password/password --truststore-password-file=/password/password \
              {{- end }}
              -c {{ .Values.extraServerArgs.cacheHeapRatio }} \
              -k {{ .Values.extraServerArgs.sequencerCacheSize }} \
              -d {{ .Values.extraServerArgs.logLevel }} \
              --log-size-quota-percentage {{ .Values.extraServerArgs.logSizeQuotaPercentage }} \
              --compactor-script {{ .Values.extraServerArgs.compactorScript }} \
              --compactor-config {{ .Values.extraServerArgs.compactorConfig }} \
              --compaction-trigger-freq-ms {{ .Values.extraServerArgs.compactorTriggerFreqMs }} \
              {{- if .Values.extraServerArgs.metricsEnabled }}
              --metrics \
              {{- end }}
              {{ .Values.service.port }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.jvmArgsFilePath }}
            - name: JAVA_OPTS
              value: |-
                {{- .Files.Get .Values.jvmArgsFilePath | nindent 16 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: corfu-data
              mountPath: /config
            {{- end }}
            {{- if .Values.tls.enabled }}
            - name: certificate
              mountPath: /certs
            - name: password
              mountPath: /password
            {{- end }}
            - name: {{ include "corfu.fullname" . }}-corfu-configs
              mountPath: /usr/share/corfu/conf
            {{- if .Values.logPersistence.enabled }}
            - name: log-dir
              mountPath: /var/log/corfu
            {{- end }}
      volumes:
      {{- if .Values.tls.enabled }}
        - name: certificate
          secret:
            secretName: {{ .Values.tls.secretName }}
        - name: password
          secret:
            secretName: {{ .Values.tls.passwordName }}
      {{- end }}
        - name: {{ include "corfu.fullname" . }}-corfu-configs
          configMap:
            name: {{ include "corfu.fullname" . }}-corfu-configs
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: corfu-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "{{ .Values.persistence.storageClass }}"
        resources:
          requests:
            storage: {{ .Values.persistence.storageSize }}
  {{- end }}
  {{- if .Values.logPersistence.enabled }}
    - metadata:
        name: log-dir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "{{ .Values.logPersistence.storageClass }}"
        resources:
          requests:
            storage: {{ .Values.logPersistence.storageSize }}
  {{- end }}

