apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: litmus
    app.kubernetes.io/component: litmus-infra
    app.kubernetes.io/instance: litmus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: litmus
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/version: 2.14.0
    helm.sh/chart: litmus-core-2.14.0
    litmuschaos.io/version: 2.14.0
  name: litmus
rules:
- apiGroups:
  - ""
  - apps
  - batch
  - extensions
  - litmuschaos.io
  - argoproj.io
  resources:
  - pods
  - pods/exec
  - pods/log
  - pods/eviction
  - jobs
  - deployments
  - daemonsets
  - statefulsets
  - events
  - configmaps
  - services
  - rollouts
  - chaosengines
  - chaosexperiments
  - chaosresults
  verbs:
  - get
  - create
  - update
  - patch
  - delete
  - list
  - watch
  - deletecollection
- apiGroups:
  - litmuschaos.io
  resources:
  - chaosengines/finalizers
  verbs:
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - list
  - update
  - delete
