apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: litmus
    app.kubernetes.io/component: litmus-infra
    app.kubernetes.io/instance: litmus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: litmus
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/version: 2.14.0
    helm.sh/chart: litmus-core-2.14.0
    litmuschaos.io/version: 2.14.0
  name: litmus