# apiVersion: cert-manager.io/v1alpha2
# kind: Certificate
# metadata:
#   name: selfsigned-cert
# spec:
#   dnsNames:
#     - example.com
#   secretName: selfsigned-cert-tls
#   issuerRef:
#     name: test-selfsigned
