{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.passwordName }}
  labels:
    {{- include "corfu.labels" . | indent 4 }}
type: Opaque
data:
  password: {{ .Values.tls.password }}
{{- end }}
