apiVersion: batch/v1
kind: Job
metadata:
  name: corfu-client-example
spec:
  template:
    spec:
        restartPolicy: OnFailure
        containers:
          - name: corfu-client
            image: corfudb/corfu-client-example:latest
            imagePullPolicy: Never
            command:
              - "sh"
              - "-c"
              - |
                java -cp *.jar org.corfudb.cloud.runtime.example.Main {{ .Values.corfuEndpoint }} {{ .Values.jobs.job }}
                {{- if .Values.tls.enabled }} \
                /certs/keystore.jks /password/password /certs/truststore.jks /password/password
                {{- end }}
            volumeMounts:
              {{- if .Values.tls.enabled }}
              - name: certificate
                mountPath: /certs
              - name: password
                mountPath: /password
              {{- end }}
        volumes:
          {{- if .Values.tls.enabled }}
          - name: certificate
            secret:
              secretName: {{ .Values.tls.certificateName }}
          - name: password
            secret:
              secretName: {{ .Values.tls.passwordName }}
          {{- end }}
