image:
  registry: "docker.io"
  repository: "corfudb/corfu-client-example"
  tag: "latest"
  pullPolicy: Always
corfuEndpoint: "corfu-0.corfu-headless.default.svc.cluster.local"
tls:
  enabled: true
  certificateName: corfu-certificate-tls
  passwordName: corfu-password
