nameOverride: "corfu"
fullnameOverride: "corfu"
branch: master
commitSha: ""
type: "config" # config or nonconfig
image:
  registry: "docker.io"
  repository: "corfudb/corfu-server"
  tag: "cloud"
  pullPolicy: IfNotPresent
imagePullSecretsEnabled: false
imagePullSecrets:
  - name: "secret"
persistence:
  enabled: true
  storageSize: 2Gi
  storageClass: "local-path"
cluster:
  type: "source"
lr:
  port: 9010
  name: "log-replication"
resources: {}
resourcesLR: {}
service:
  port: 9000
  healthPort: 8080
serviceAccount:
  create: true
  annotations: {}
  name: "corfu"
podSecurityContext:
  fsGroup: 900
  runAsGroup: 900
  runAsUser: 900
podSecurityPolicy:
  name: corfu
tls:
  enabled: true
  certificate:
    enabled: true
    certificateName: corfu-certificate
    issuer:
      kind: Issuer
      name: ca-issuer
  secretName: corfu-certificate-tls
  passwordName: corfu-password
  password: "MTIzNDU2"
jvmArgsFilePath: "java_opts/default"
jvmArgsFilePathLR: "java_opts/lr"
extraServerArgs:
  cacheHeapRatio: 0.2
  sequencerCacheSize: "5000000"
  logLevel: DEBUG
  logSizeQuotaPercentage: 40
  compactorScript: "/usr/share/corfu/scripts/compactor_runner.py"
  compactorConfig: "/usr/share/corfu/conf/corfu-compactor-config.yml"
  compactorTriggerFreqMs: 900000
  metricsEnabled: true
version:
  new: false