branch: master
commitSha: ""
type: "config" # config or nonconfig
replicas: 3
image:
  registry: "docker.io"
  repository: "corfudb/corfu-server"
  tag: "cloud"
  pullPolicy: Always
imagePullSecretsEnabled: false
imagePullSecrets:
  - name: "secret"
persistence:
  enabled: true
  storageSize: 2Gi
  storageClass: "local-path"
logPersistence:
  enabled: true
  storageSize: 1Gi
  storageClass: "local-path"
resources: {}
service:
  port: 9000
serviceAccount:
  create: true
  annotations: {}
  name: "corfu"
podSecurityContext:
  fsGroup: 900
  runAsGroup: 900
  runAsUser: 900
podSecurityPolicy:
  name: corfu
tls:
  enabled: false
  issuer: ca-issuer
  certificateName: corfu-certificate
  passwordName: corfu-password
  password: "MTIzNDU2"
includeJVMArgs: true
extraServerArgs:
  cacheHeapRatio: 0.2
  sequencerCacheSize: "5000000"
  logLevel: DEBUG
  logSizeQuotaPercentage: 40
  metricsEnabled: true

