tls:
  keystore: "/certs/keystore.jks"
  keystorePassword: "/password/password"

  truststore: "/certs/truststore.jks"
  truststorePassword: "/password/password"

benchmark:

  warmup:
    iterations: 1
    timeInMinutes: 1

  measurement:
    iterations: 1
    timeInMinutes: 5

  threads: 2
  forks: 4

  coolOffPeriodMinutes: 240

  randomizedPut:
    minDataSize: "1024"
    maxDataSize: "524288"
    numRuntimes:
      - "1"
      #- "4"

    numTables:
      #- "1"
      #- "4"
      - "8"
      #- "16"
      - "32"


  put:
    putNumRuntimes:
      - "1"
      #- "4"

    putNumTables:
      - "1"
      #- "4"
      #- "8"
      - "16"
      #- "32"

    dataSize:
      - "1024"
      #- "2048"
      #- "4096"
  get:
    getNumRuntimes:
      - "1"
      #- "4"

    getNumTables:
      - "1"
      #- "4"

    dataSizeForGetOperation:
      - "1024"
      #- "2048"
      #- "4096"
      #- "65536"