name: Cloud Corfu Cleint Build

on: workflow_dispatch

jobs:
  corfu-client-docker:
    runs-on: ubuntu-latest

    env:
      PKG_USERNAME: ${{ secrets.pkg_username }}
      PUBLISH_TOKEN: ${{ secrets.publish_token }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to the Registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER_NAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build docker image
        working-directory: cloud/corfu/corfu-client-example
        run: |
          ./docker-build.sh
          docker push corfudb/corfu-client-example:latest