name: Cloud Corfu Cleint Build

on: workflow_dispatch

jobs:
  corfu-client-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login to the Registry
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER_NAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        working-directory: cloud/corfu/corfu-client-example
        run: |
          ./docker-build.sh
          docker push corfudb/corfu-client-example:latest