name: Universe Framework Artifacts

on:
  push:
    branches:
      - master
    paths:
      - 'universe/**'
      - '!universe/doc/**'
      - '.github/workflows/publish-universe-artifacts.yml'

jobs:
  publish_universe_artifacts:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    env:
      PKG_USERNAME: ${{ secrets.pkg_username }}
      PUBLISH_TOKEN: ${{ secrets.publish_token }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'
          check-latest: true
          cache-dependency-path: '**/pom.xml'

      - name: Cache local Gradle repository
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Publish artifacts
        working-directory: ./universe
        run: ./gradlew publish
