name: Pull Request Universe Framework

on:
  pull_request:
    paths:
    - 'universe/**'
    - '!universe/doc/**'
    - '.github/workflows/pull_request_universe.yml'

jobs:
  test:
    name: Universe Framework unit tests
    runs-on: ubuntu-latest

    env:
      PKG_USERNAME: ${{ secrets.pkg_username }}
      PUBLISH_TOKEN: ${{ secrets.publish_token }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '11'
        check-latest: true
        cache-dependency-path: '**/pom.xml'

    - name: Cache local Gradle repository
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build Universe Framework with Gradle
      working-directory: ./universe
      run: ./gradlew check
