name: Pull Request Benchmarks

on:
  pull_request:
    paths:
    - 'benchmarks/**'
    - '.github/workflows/pull_request_benchmarks.yml'

jobs:
  benchmarks_check:
    name: Benchmark checks
    runs-on: ubuntu-latest

    env:
      PKG_USERNAME: ${{ secrets.pkg_username }}
      PUBLISH_TOKEN: ${{ secrets.publish_token }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '21'
        check-latest: true
        cache-dependency-path: '**/pom.xml'

    - name: Cache local Gradle repository
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - uses: satackey/action-docker-layer-caching@v0.0.8
      continue-on-error: true

    - name: Check benchmarks module
      working-directory: ./benchmarks
      run: ./gradlew check

    #- name: push docker image
    #  working-directory: ./benchmarks
      #run: |
      #  ./gradlew jmhJar
      #  echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u ${{ secrets.DOCKER_USER_NAME }} --password-stdin
      #  docker build -t corfudb/corfudb-cloud-benchmarks:latest .
      #  docker push corfudb/corfudb-cloud-benchmarks:latest
