name: Corfu Benchmarks

on:
  push:
    branches:
      - master
    paths:
      - 'benchmarks/**'
      - '.github/workflows/run_benchmarks.yml'

jobs:
  run_benchmarks:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    env:
      PKG_USERNAME: ${{ secrets.pkg_username }}
      PUBLISH_TOKEN: ${{ secrets.publish_token }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          check-latest: true
          cache-dependency-path: '**/pom.xml'

      - name: Cache local Gradle repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Benchmarks
        working-directory: ./benchmarks
        # Disable benchmarks
        #run: ./gradlew jmh
